<a href="https://colab.research.google.com/github/Adityas8081/Customer-Shopping-Analysis/blob/main/customer_shopping_behavioripynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [103]:
import pandas as pd
df = pd.read_csv("customer_shopping_behavior.csv")

In [104]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [106]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [107]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [108]:
from numpy import median
df["Review Rating"] = df.groupby("Category")["Review Rating"].transform(lambda x: x.fillna(x.median()))

In [109]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [110]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ","_")
df = df.rename(columns={"purchase_amount_(usd)" : "purchase_amount"})

In [111]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [112]:
# Create a columns age_group
labels = ["Young Adult", "Adult","Middle-aged","Senior"]
df["age_group"] = pd.qcut(df["age"],q=4, labels = labels)

In [113]:
df[["age","age_group"]].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [114]:
#Create columns purchase_frequency_days
frequency_mapping = {
    "Fortnightly":14,
    "Weekly":7,
    "Monthly":30,
    "Quaterly":90,
    "Bi-Weekly":15,
    "Annually":365,
    "Every 3 Months":90
}

df["purchase_frequency_days"] = df["frequency_of_purchases"].map(frequency_mapping)

In [115]:
df[["purchase_frequency_days","frequency_of_purchases"]].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                      NaN              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                      NaN              Quarterly

In [116]:
df[["discount_applied","promo_code_used"]]

     discount_applied promo_code_used
0                 Yes             Yes
1                 Yes             Yes
2                 Yes             Yes
3                 Yes             Yes
4                 Yes             Yes
...               ...             ...
3895               No              No
3896               No              No
3897               No              No
3898               No              No
3899               No              No

[3900 rows x 2 columns]

In [117]:
(df["discount_applied"]== df["promo_code_used"]).all()

np.True_

In [118]:
df = df.drop("promo_code_used",axis=1)

In [119]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [120]:
import sqlite3

conn = sqlite3.connect("project.db")

In [121]:
df.to_sql("data_table", conn, if_exists="replace", index=False)

3900

In [122]:
query = "SELECT * FROM data_table LIMIT 5"
pd.read_sql(query, conn)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14.0
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14.0
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7.0
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7.0
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365.0

In [123]:
# 1.What is the total revenue generated by male vs. female customers?
query = "SELECT gender, SUM(purchase_amount) AS revenue FROM data_table GROUP BY gender"
pd.read_sql(query, conn)

   gender  revenue
0  Female    75191
1    Male   157890

In [124]:
# 2.Which customers used a discount but still spent more than the average purchase amount?
query = """SELECT customer_id, purchase_amount FROM data_table
WHERE discount_applied = 'Yes'
AND purchase_amount > (
    SELECT AVG(purchase_amount) FROM data_table)"""
pd.read_sql(query, conn)

     customer_id  purchase_amount
0              2               64
1              3               73
2              4               90
3              7               85
4              9               97
..           ...              ...
834         1667               64
835         1671               73
836         1673               73
837         1674               62
838         1676               90

[839 rows x 2 columns]

In [125]:
# 3.Which are the top 5 products with the highest average review rating?
query = """SELECT item_purchased, ROUND(AVG(review_rating),2) as "Average Product Rating"
FROM data_table
group by item_purchased
order by AVG(review_rating) desc
LIMIT 5;"""
pd.read_sql(query, conn)

  item_purchased  Average Product Rating
0         Gloves                    3.86
1        Sandals                    3.84
2          Boots                    3.82
3            Hat                    3.80
4          Skirt                    3.78

In [126]:
# 4.Compare the average Purchase Amounts between Standard and Express Shipping.
query = """SELECT shipping_type, ROUND(AVG(purchase_amount),2) FROM data_table
WHERE shipping_type in ("Standard","Express")
group by shipping_type"""
pd.read_sql(query, conn)

  shipping_type  ROUND(AVG(purchase_amount),2)
0       Express                          60.48
1      Standard                          58.46

In [127]:
# 5.Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
query = """SELECT subscription_status, COUNT(customer_id) as total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       SUM(purchase_amount) AS total_revenue
FROM data_table
GROUP BY subscription_status
order by total_revenue, avg_spend desc;"""
pd.read_sql(query, conn)

  subscription_status  total_customers  avg_spend  total_revenue
0                 Yes             1053      59.49          62645
1                  No             2847      59.87         170436

In [128]:
# 6.Which 5 products have the highest percentage of purchases with discounts applied?
query = """SELECT item_purchased ,ROUND(100*SUM(CASE WHEN discount_applied = 'Yes' Then 1 ELSE 0 END)/COUNT(*),2) as discount_rate
FROM data_table
group by item_purchased
order by discount_rate desc
limit 5;"""
pd.read_sql(query, conn)

  item_purchased  discount_rate
0            Hat           50.0
1       Sneakers           49.0
2           Coat           49.0
3        Sweater           48.0
4          Pants           47.0

In [129]:
# 7.Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
query = """SELECT
CASE
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
END AS customer_segment,
COUNT(*) AS total_customers
FROM data_table
GROUP BY customer_segment;"""
pd.read_sql(query, conn)

  customer_segment  total_customers
0            Loyal             3116
1              New               83
2        Returning              701

In [130]:
# 8.What are the top 3 most purchased products within each category?
query = """SELECT rank ,category, item_purchased, total_orders
FROM (
    SELECT category, item_purchased, COUNT(*) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rank
    FROM data_table
    GROUP BY category, item_purchased
)
WHERE rank <= 3;
"""
pd.read_sql(query, conn)

    rank     category item_purchased  total_orders
0      1  Accessories        Jewelry           171
1      2  Accessories     Sunglasses           161
2      3  Accessories           Belt           161
3      1     Clothing          Pants           171
4      2     Clothing         Blouse           171
5      3     Clothing          Shirt           169
6      1     Footwear        Sandals           160
7      2     Footwear          Shoes           150
8      3     Footwear       Sneakers           145
9      1    Outerwear         Jacket           163
10     2    Outerwear           Coat           161

In [131]:
# 9.Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
query = """SELECT subscription_status,
       COUNT(*) AS repeat_buyers
FROM data_table
WHERE previous_purchases > 5
GROUP BY subscription_status;
"""
pd.read_sql(query, conn)

  subscription_status  repeat_buyers
0                  No           2518
1                 Yes            958

In [132]:
# 10.What is the revenue contribution of each age group?
query = """SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM data_table
GROUP BY age_group
ORDER BY total_revenue DESC;
"""
pd.read_sql(query, conn)

     age_group  total_revenue
0  Young Adult          62143
1  Middle-aged          59197
2        Adult          55978
3       Senior          55763

In [133]:
result=pd.read_sql(query, conn)
result.to_csv("Customer_shopping_FinalClean.csv", index=False)

In [135]:
final_df = df.copy()
df.to_csv("Final_Cleaned_Data.csv", index=False)